dist: xenial

language: python

python:
  - 3.7
  - 3.6
matrix:
  include:
    - python: 3.7
      env: TOXENV=docs
    - python: 3.7
      env: TOXENV=lint

addons:
  apt:
    packages:
      - bluez
      - libbluetooth-dev

install:
  - pip install tox tox-travis

script:
  - tox
